config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  get '/search' => 'homes#search'
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :consumers, controllers: {
    sessions:      'consumers/sessions',
    passwords:     'consumers/passwords',
    registrations: 'consumers/registrations'
  }

  devise_for :fermers, controllers: {
    sessions:      'fermers/sessions',
    passwords:     'fermers/passwords',
    registrations: 'fermers/registrations'
  }

    namespace :consumers do
      get 'consumers/withdraw'=> 'consumers#withdraw'
      patch 'consumers/change' => 'consumers#change'
      put 'consumers/change' => 'consumers#change'
      get '/search' => 'searches#search'
      resources :searches,only: [:index]
      resources :consumers,only: [:edit,:update,:show]
      resources :cards,only: [:create,:destroy]
      resources :fermers do
        resources :fermer_reviews,only: [:index,:show,:create,:destroy]
        resource :book_marks,only: [:create,:destroy]
      end
      resources :columns do
        resource :column_comments,only: [:index,:show,:create,:destroy], shallow: true
        resource :column_favorites,only: [:create,:destroy], shallow: true
      end
      resources :cart_products,only: [:index,:create,:update,:destroy]
      resources :destinations ,only: [:show,:index,:edit,:update,:create,:destroy]
      resources :products ,only: [:show,:index] do
        resource :product_comment,only: [:show,:create,:destroy], shallow: true
        resource :product_favorite,only: [:create,:destroy], shallow: true
      end
      get 'orders/confirm' => 'orders#confirm'
      post 'orders/pay' => 'orders#pay'
      get 'orders/finish' => 'orders#finish'
      resources :orders ,only: [:new,:create,:index,:show]
      delete 'consumers/cart_products/destroy_all'  => 'cart_products#destroy_all'
    end


    namespace :fermers do
      resources :fermers,only:[:show,:edit,:update]
      get '/search' => 'searches#search'
      get 'fermers/withdraw'=> 'fermers#withdraw'
      patch 'fermers/change' => 'fermers#change'
      put 'fermers/change' => 'fermers#change'
      resources :searches,only: [:index]
      post 'products/filter_brand' => 'products#filter_brand'
      resources :columns
      resources :columns_comments,only: [:index,:show], shallow: true
      resources :columns_favorites,only: [:index], shallow: true
      resources :products
      resources :products_comments,only: [:index,:show], shallow: true
      resources :products_favorites,only: [:index], shallow: true
      resources :order_products,only: [:update]
      resources :orders,only: [:show,:index,:update]
      resources :consumers,only: [:show,:index]
      resources :addresses ,only: [:show,:index,:edit,:update,:create,:destroy]
    end


    namespace :admins do
      get 'homes/top'
      get '/search' => 'searches#search'
      resources :searches,only: [:index]
      resources :consumers,only: [:show,:index,:destroy]
      resources :fermers,only: [:index,:show,:destroy]
      resources :categories,only: [:index,:create,:edit,:update,:destroy]
      resources :brands,only: [:index,:create,:edit,:update,:destroy]
      resources :products,only: [:index,:show,:destroy]
      resources :orders,only: [:show,:index,:destroy]
      resources :columns,only: [:index,:show,:destroy]
      resources :column_comments,only: [:index,:show]
      resources :products_comments,only: [:index,:show]
    end
end

app/controllers/admins/consumers_controller.rb
class Admins::ConsumersController < ApplicationController
	layout 'admin'
  before_action :authenticate_admin!
  def index
  	@consumers = Consumer.all
  end
   def show
  	@consumer = Consumer.find(params[:id])
  end
  private
  def consumer_params
       params.require(:consumer).permit(:last_name, :first_name, :kana_last_name, :kana_first_name,:gender,:age,:prefecture_code, :address_city,:address_street,:address_building, :postcode, :phone, :email,:withdraw,:profile_image)
    end
end

app/controllers/consumers/base.rb
class Consumers::BaseController < ApplicationController
     layout 'consumer'
end

app/controllers/consumers/book_marks_controller.rb
class Consumers::BookMarksController < ApplicationController
	layout 'consumer'
  before_action :authenticate_consumer!
	def create
      @fermer = Fermer.find(params[:fermer_id])
      @book_mark = @fermer.book_marks.new(consumer_id: current_consumer.id)
      @book_mark.save
  end
  def destroy
      @fermer = Fermer.find(params[:fermer_id])
      @book_mark = current_consumer.book_marks.find_by(fermer_id: @fermer.id)
      @book_mark.destroy!
  end

  private
  def redirect
    case params[:redirect_id].to_i
    when 0
      redirect_to consumers_fermers_path
    when 1
      redirect_to consumers_fermers_path(@fermer)
    end
  end
end

app/controllers/consumers/cards_controller.rb
class Consumers::CardsController < ApplicationController
	layout 'consumer'
  before_action :authenticate_consumer!
	require "payjp"
	def create
		@consumer = current_consumer
    Payjp.api_key = ENV["PAYJP_SECRET_KEY"]
    if params['payjp-token'].blank?
      redirect_to consumers_consumer_path(@consumer)
    else
        customer = Payjp::Customer.create(
        description: '登録テスト',
        email: current_consumer.email,
        card: params['payjp-token'],
        metadata: {consumer_id: current_consumer.id}
        )
        @card = Card.new(consumer_id: current_consumer.id, customer_id: customer.id, payjp_id: customer.default_card)
        if @card.save
          redirect_to consumers_consumer_path(@consumer)
        else
         redirect_to consumers_consumer_path(@consumer)
        end
    end
  end
  def destroy
    @card = Card.find_by(consumer_id: current_consumer.id)
    Payjp.api_key = ENV["PAYJP_SECRET_KEY"]
    @customer = Payjp::Customer.retrieve(@card.customer_id)
    @customer.delete
    @card.delete
    redirect_to consumers_consumer_path(current_consumer)
  end
end

app/controllers/consumers/cart_products_controller.rb
class Consumers::CartProductsController < ApplicationController
	layout 'consumer'
	before_action :authenticate_consumer!
  	def index
		@cart_product = CartProduct.new
		@cart_products = CartProduct.where(consumer_id: current_consumer)
		@total_price = 0
    @cart_products.each do |cart_product|

    @total_price += (cart_product.product.unit_price * cart_product.quantity)
    end
	end

	def create
		@cart_product = CartProduct.new(cart_product_params)
		@cart_product.consumer_id = current_consumer.id
		if @cart_product.save
			redirect_to consumers_cart_products_path(@cart_product)
		else
			redirect_to consumers_product_path(@cart_product.product_id)
		end
	end

    def update
      @cart_product = CartProduct.find(params[:id])
  	  @cart_product.update!(cart_product_params)
  	  @consumer = Consumer.find(current_consumer.id)
  	  redirect_back(fallback_location: consumers_cart_products_path)
  	end

    def destroy
      @cart_product = CartProduct.find(params[:id])
	  @cart_product.destroy
	  redirect_back(fallback_location: consumers_cart_products_path)
    end

    def destroy_all
	  consumer = Consumer.find(current_consumer.id)
	 if consumer.cart_products.destroy_all
	 	flash[:notice] = "カートの商品を全て削除しました。"
	  redirect_to consumers_products_path
	else
		render 'index'
	end
    end

  private

    def cart_product_params
	  params.require(:cart_product).permit(:consumer_id,:product_id,:quantity,:unit_price)
    end

  end

app/controllers/consumers/column_comments_controller.rb
class Consumers::ColumnCommentsController < ApplicationController
	layout 'consumer'
	before_action :authenticate_consumer!
	def create
	    @column = Column.find(params[:column_id])
		@comment = @column.column_comments.build(column_comment_params)
		@comments = @column.column_comments
		@comment.consumer_id = current_consumer.id
		@comment.save
	end

	def destroy
		@column = Column.find(params[:column_id])
		@comments = @column.column_comments
		@comment = current_consumer.column_comments.find(params[:id])
		@comment.destroy
	end
	private
	def column_comment_params
			params.require(:column_comment).permit(:comment, :consumer_id, :column_id)
	end
end

app/controllers/consumers/column_favorites_controller.rb
class Consumers::ColumnFavoritesController < ApplicationController
	layout 'consumer'
    before_action :authenticate_consumer!
	before_action :column_params
	def create
        @column = Column.find(params[:column_id])
        @favorite = @column.column_favorites.new(consumer_id: current_consumer.id)
        @favorite.save
    end
    def destroy
        @column = Column.find(params[:column_id])
        @favorite = current_consumer.column_favorites.find_by(column_id: @column.id)
        @favorite.destroy!
    end
    private
    def favorite_params
        params.require_params(:favorite).permit(:column_id)
    end
    def column_params
        @column = Column.find(params[:column_id])
    end
    def redirect
      case params[:redirect_id].to_i
      when 0
        redirect_to consumers_columns_path
      when 1
        redirect_to consumers_column_path(@column)
      end
    end
end

app/controllers/consumers/columns_controller.rb
class Consumers::ColumnsController < ApplicationController
	layout 'consumer'
	def index
		if params[:fermer_id]
			@columns = Column.where(fermer_id: params[:fermer_id])
		else
			@columns = Column.all
		end
	end

	def show
		@column = Column.find(params[:id])
		@consumer = Consumer.find(@column.fermer_id)
		@comment = ColumnComment.new
		@comments = @column.column_comments
		@favorite = ColumnFavorite.new
	end
	private
	def column_params
		params.require(:column).permit(:title, :body,:fermer_id)
	end
end

app/controllers/consumers/confirmations_controller.rb
# frozen_string_literal: true

class Consumers::ConfirmationsController < Devise::ConfirmationsController
  layout 'consumer'
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/consumers/consumers_controller.rb
class Consumers::ConsumersController < ApplicationController
 layout 'consumer'
 before_action :authenticate_consumer!
 require "payjp"

  def show
  	@consumer = Consumer.find(params[:id])
      @card = Card.new
      @cards = Card.find_by(consumer_id: current_consumer.id)
      if @cards
        Payjp.api_key = ENV["PAYJP_SECRET_KEY"]
        customer = Payjp::Customer.retrieve(@cards.customer_id)
        @default_card_information = customer.cards.retrieve(@cards.payjp_id)
      end
   end
  def edit
  	@consumer = Consumer.find(params[:id])
  	unless current_consumer.nil? || current_consumer.id == current_consumer.id
			flash[:warning] = "アクセス権がありません"
			redirect_to consumer_path(current_consumer)
		end
  end
  def update
  	if current_consumer.update(consumer_params)
			flash[:success] =  "更新に成功しました"
			redirect_to consumers_consumer_path(current_consumer)
		else
			flash[:warning] = "入力内容を確認してください"
			render :edit
		end
  end
  def change
    current_consumer.update(withdraw: true)
    reset_session
    redirect_to root_path
  end
  def withdraw
  end

  private
   def consumer_params
       params.require(:consumer).permit(:last_name, :first_name, :kana_last_name, :kana_first_name,:gender,:age,:prefecture_code, :address_city,:address_street,:address_building, :postcode, :phone, :email,:withdraw,:profile_image)
    end
end

app/controllers/consumers/destinations_controller.rb
class Consumers::DestinationsController < ApplicationController
	layout 'consumer'
	before_action :authenticate_consumer!
	def index
		@destination = Destination.new
		@destinations = Destination.all
	end

	def create
		@destination = Destination.new(destination_params)
		@destination.consumer_id = current_consumer.id
		if @destination.save!
			@destination.update!(address: @destination.prefecture_name + @destination.address_city + @destination.address_street + @destination.address_building)
			redirect_back(fallback_location: consumers_destinations_path)
		else
			redirect_back(fallback_location: consumers_destinations_path)
		end
	end

	def edit
		@destination = Destination.find(params[:id])
	end

	def update
		@destination = Destination.find(params[:id])
		if @destination.update(destination_params)
			redirect_to members_destinations_path
		else
			redirect_to members_destinations_path
		end
    end
	def destroy
		@destination = Destination.find(params[:id])
		@destination.destroy
		redirect_to consumers_destinations_path
	end


private

	def destination_params
		params.require(:destination).permit(:consumer_id,:prefecture_code,:address_city,:address_street,:address_building, :postcode, :name, :address)
	end
end

app/controllers/consumers/fermer_reviews_controller.rb
class Consumers::FermerReviewsController < ApplicationController
	layout 'consumer'
	before_action :authenticate_consumer!
	def create
	    @fermer = Fermer.find(params[:fermer_id])
		@review = @fermer.fermer_reviews.build(fermer_review_params)
		@reviews = @fermer.fermer_reviews
		@review.consumer_id = current_consumer.id
		@review.save
	end

	def destroy
	    @fermer = Fermer.find(params[:fermer_id])
	    @reviews = @fermer.fermer_reviews
		@review = current_consumer.fermer_reviews.find(params[:id])
		@review.destroy
	end

	private
	def fermer_review_params
		params.require(:fermer_review).permit(:comment, :consumer_id, :fermer_id,:rate,:title)
	end
end

app/controllers/consumers/fermers_controller.rb
class Consumers::FermersController < ApplicationController
	layout 'consumer'
  before_action :authenticate_consumer!
  def index
  	@fermers = Fermer.all
    @consumer = current_consumer
    # @bookmarks = Bookmark.where(consumer_id: @consumer.id).all
  end
  def show
  	@fermer = Fermer.find(params[:id])
    @book_mark = BookMark.new
    @review = FermerReview.new
    @reviews = @fermer.fermer_reviews
  end
  private
  def fermer_params
  	params.require(:fermer).permit(:last_name, :first_name, :kana_last_name, :kana_first_name, :postcode,:prefecture_code, :address_city, :address_street, :address_building, :phone,:garden,:home_page,:profile_image)
  end
end

app/controllers/consumers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Consumers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  layout 'consumer'
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/consumers/passwords_controller.rb
# frozen_string_literal: true

class Consumers::PasswordsController < Devise::PasswordsController
  layout 'consumer'
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/consumers/product_comments_controller.rb
class Consumers::ProductCommentsController < ApplicationController
	layout 'consumer'
	before_action :authenticate_consumer!
	def create
	    @product = Product.find(params[:product_id])
		@comment = @product.product_comments.build(product_comment_params)
		@comment.consumer_id = current_consumer.id
		 if @comment.save
		 	flash[:success] = "Comment was successfully created."
		 	render 'index'
		 else
           redirect_to consumers_products_path(@product)
         end
	end

	def destroy
	    @product = Product.find(params[:product_id])
		@comments = @product.product_comments
		@comment = current_consumer.product_comments.find(params[:id])
		@comment.destroy
	end

	private
	def product_comment_params
		params.require(:product_comment).permit(:comment, :consumer_id, :product_id,:rate,:title)
	end
end

app/views/consumers/consumers/edit.html.erb
<div class="row" style= "width: 80%; margin: 20px auto;">
  <div class="form-horizontal">
    <h4 style="margin-bottom: 20px; border-left: 2px solid #2D6F4C; padding: 10px;">プロフィール編集画面</h4>
  </div>
</div>

<div class="row my-3">
  <div class="offset-3 col-6">

    <%= form_for(@consumer, url:consumers_consumer_path,  local: true) do |f| %>
    <div class="form-group">
      <%= f.label :プロフィール画像, class: "brown-border px-3" %>
      <%= f.attachment_field :profile_image %>
    </div>
    <div class="form-group">
      <%= f.label :氏名, class: "brown-border px-3" %>
      <div class="row">
        <%= f.text_field :last_name, class: "form-control col-4"%>
        <%= f.text_field :first_name, class: "brown-border px-3" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :フリガナ, class: "brown-border px-3" %>
      <div class="row">y
        <%= f.text_field :kana_last_name, class: "form-control offset-1 col-4"%>
          <%= f.text_field :kana_first_name, class: "form-control col-4"%>
      </div>
    </div>
    <div class="form-group">
     <%= f.radio_button :gender, :man %>
     <label >男性</label>
     <%= f.radio_button :gender, :woman %>
     <label >女性</label>
   </div>
   <div class="form-group">
    <%= f.radio_button :age, :ten %>
    <label >10代</label>
    <%= f.radio_button :age, :twenty %>
    <label >20代</label>
    <%= f.radio_button :age, :thirty %>
    <label >30代</label>
    <%= f.radio_button :age, :forty %>
    <label >40代</label>
    <%= f.radio_button :age, :fifty %>
    <label >50代以上</label>
  </div>
  <div class="form-group">
    <%= f.label :電話番号, class: "brown-border px-3" %>
    <%= f.text_field :phone, class: "form-control offset-1 col-8"%>
  </div>

  <div class="form-group">
    <%= f.label :メールアドレス, class: "brown-border px-3" %>
    <%= f.email_field :email, class: "form-control offset-1 col-8"%>
  </div>
  <div class="field">
   <%= f.label :郵便番号, class: "brown-border px-3" %>
   <%= f.text_field :postcode, class: "form-control offset-1 col-8"%>
 </div>
 <div class="field">
   <%= f.label :都道府県, class: "brown-border px-3" %>
   <%= f.collection_select :prefecture_code, JpPrefecture::Prefecture.all, :code, :name %>
 </div>
 <div class="field">
   <%= f.label :市町村, class: "brown-border px-3" %>
   <%= f.text_field :address_city, class: "form-control offset-1 col-8" %>
 </div>
 <div class="field">
  <%= f.label :番地, class: "brown-border px-3" %>
  <%= f.text_field :address_street, class: "form-control offset-1 col-8" %>
</div>
<div class="field">
 <%= f.label :建物, class: "brown-border px-3" %>
 <%= f.text_field :address_building, class: "form-control offset-1 col-8" %>
</div>


<div class="row">
  <%= f.submit "編集内容を保存する", class: "btn btn-outline-success offset-3 mt-3" %>
</div>
<% end %>

</div>

<div class="col-2 d-flex flex-column align-items-end">
  <%= link_to "退会する" ,  consumers_consumers_withdraw_path,method: :get, class: "btn btn-danger mt-auto" %>
</div>
</div>

app/views/consumers/consumers/show.html.erb
		<h4 style="margin-bottom: 20px; border-left: 2px solid #2D6F4C; padding: 10px;">マイページ</h4>
<div class="show-container" style="width:50%; margin: 20px auto;">
	<table class="table table-bordered">
		<tr>
			<th style=“background-color: #DAD7D7; border-bottom: 1px solid #fff;“>プロフィール画像</th>
			<td>
				<% if @consumer.profile_image.present? %>
	     			<%= attachment_image_tag @consumer,:profile_image, :fill, 200, 200 %>
				<% else %>
					<%= image_tag 'no_image.jpg',size: '200*200'%>
				<% end %>
			</td>
		</tr>
		<tr>
			<th style=“background-color: #DAD7D7; border-bottom: 1px solid #fff;“>氏名</th>
			<td><%= @consumer.name %></td>
		</tr>
		<tr>
			<th style=“background-color: #DAD7D7; border-bottom: 1px solid #fff;“>電話番号</th>
			<td><%= @consumer.phone %></td>
		</tr>
		<tr>
			<th style=“background-color: #DAD7D7; border-bottom: 1px solid #fff;“>メールアドレス</th>
			<td style=“border-bottom: 1px solid #DAD7D7;“><%= @consumer.email %></td>
		</tr>
		<td><h5>登録情報</h5>
			<%= link_to '編集する', edit_consumers_consumer_path, class: "btn btn-outline-primary" %>
		</td>
	</table>

	<table>
		<td><h5>カード情報登録・確認</h5>
			<% if @default_card_information.nil? %>
				<%= form_for(@card,url:consumers_cards_path,method: :post) do |f| %>
				 <script
		          type="text/javascript"
		          src="https://checkout.pay.jp/"
		          class="payjp-button"
		          data-key="<%= ENV["PAYJP_PUBLIC_KEY"] %>"
		          data-submit-text="カード番号の登録する"
		          data-text="カード番号の登録"
		          data-partial="false">
	       		</script>
	       		<% end %>
	       	<%else%>
		       	<%="**** **** **** " + @default_card_information.last4 %><br>
		       	有効期限
		       	<% exp_month = @default_card_information.exp_month.to_s %>
				<% exp_year = @default_card_information.exp_year.to_s.slice(2,3)%>
				<%= exp_month + " / " + exp_year%>
			<div>
				<%= link_to"カード情報を削除する",consumers_card_path(@cards),method: :delete%>
			</div>
	       	<% end %>
		</td>
	</table>

	<th><h4 style="margin-bottom: 20px; border-left: 2px solid #2D6F4C; padding: 10px;">配送先</h4>
		<%= link_to consumers_destinations_path do %>
		一覧を見る<span class="glyphicon glyphicon-chevron-right"></span>
		<% end %>
		<hr>
		<h4 style="margin-bottom: 20px; border-left: 2px solid #2D6F4C; padding: 10px;">注文履歴</h4>
		<%= link_to consumers_orders_path do %>
		一覧を見る<span class="glyphicon glyphicon-chevron-right"></span>
		<% end %>
	</th>
</div>

app/views/consumers/consumers/withdraw.html.erb
<div class="container my-5">
  <div class="row">
    <div class="offset-1">
      <h1 class="red-border px-3">本当に退会しますか？</h1>
    </div>
  </div>
  <div class="row my-5">
    <div class="offset-2">
      <p>退会すると、会員登録情報やこれまでの購入履歴が閲覧できなくなります。</p>
      <p>退会する場合は、「退会する」をクリックしてください。</p>
    </div>
  </div>
  <div >
    <div class="offset-3 col-2">
      <%= link_to "退会しない" ,root_path(@consumer) %>
    </div>
    <div class="offset-2 col-2">
    <%= link_to "退会する" , consumers_consumers_change_path,method: :patch %>
    </div>
  </div>
</div>