config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  get '/search' => 'homes#search'
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :consumers, controllers: {
    sessions:      'consumers/sessions',
    passwords:     'consumers/passwords',
    registrations: 'consumers/registrations'
  }

  devise_for :fermers, controllers: {
    sessions:      'fermers/sessions',
    passwords:     'fermers/passwords',
    registrations: 'fermers/registrations'
  }

    namespace :consumers do
      get 'consumers/withdraw'=> 'consumers#withdraw'
      patch 'consumers/change' => 'consumers#change'
      put 'consumers/change' => 'consumers#change'
      get '/search' => 'searches#search'
      resources :searches,only: [:index]
      resources :consumers,only: [:edit,:update,:show]
      resources :cards,only: [:create,:destroy]
      resources :fermers do
        resources :fermer_reviews,only: [:index,:show,:create,:destroy]
        resource :book_marks,only: [:create,:destroy]
      end
      resources :columns do
        resource :column_comments,only: [:index,:show,:create,:destroy], shallow: true
        resource :column_favorites,only: [:create,:destroy], shallow: true
      end
      resources :cart_products,only: [:index,:create,:update,:destroy]
      resources :destinations ,only: [:show,:index,:edit,:update,:create,:destroy]
      resources :products ,only: [:show,:index] do
        resource :product_comment,only: [:show,:create,:destroy], shallow: true
        resource :product_favorite,only: [:create,:destroy], shallow: true
      end
      get 'orders/confirm' => 'orders#confirm'
      post 'orders/pay' => 'orders#pay'
      get 'orders/finish' => 'orders#finish'
      resources :orders ,only: [:new,:create,:index,:show]
      delete 'consumers/cart_products/destroy_all'  => 'cart_products#destroy_all'
    end


    namespace :fermers do
      resources :fermers,only:[:show,:edit,:update]
      get '/search' => 'searches#search'
      get 'fermers/withdraw'=> 'fermers#withdraw'
      patch 'fermers/change' => 'fermers#change'
      put 'fermers/change' => 'fermers#change'
      resources :searches,only: [:index]
      post 'products/filter_brand' => 'products#filter_brand'
      resources :columns
      resources :columns_comments,only: [:index,:show], shallow: true
      resources :columns_favorites,only: [:index], shallow: true
      resources :products
      resources :products_comments,only: [:index,:show], shallow: true
      resources :products_favorites,only: [:index], shallow: true
      resources :order_products,only: [:update]
      resources :orders,only: [:show,:index,:update]
      resources :consumers,only: [:show,:index]
      resources :addresses ,only: [:show,:index,:edit,:update,:create,:destroy]
    end


    namespace :admins do
      get 'homes/top'
      get '/search' => 'searches#search'
      resources :searches,only: [:index]
      resources :consumers,only: [:show,:index,:destroy]
      resources :fermers,only: [:index,:show,:destroy]
      resources :categories,only: [:index,:create,:edit,:update,:destroy]
      resources :brands,only: [:index,:create,:edit,:update,:destroy]
      resources :products,only: [:index,:show,:destroy]
      resources :orders,only: [:show,:index,:destroy]
      resources :columns,only: [:index,:show,:destroy]
      resources :column_comments,only: [:index,:show]
      resources :products_comments,only: [:index,:show]
    end
end

app/controllers/admins/fermers_controller.rb
class Admins::FermersController < ApplicationController
	layout 'admin'
  before_action :authenticate_admin!
  def index
  	@fermers = Fermer.all
  end
  def show
  	@fermer = Fermer.find(params[:id])
    @reviews = @fermer.fermer_reviews
  end
  private
  def fermer_params
  	params.require(:fermer).permit(:last_name, :first_name, :kana_last_name, :kana_first_name, :postcode,:prefecture_code, :address_city, :address_street, :address_building, :phone,:garden,:home_page,:profile_image)
  end
end

app/controllers/consumers/fermers_controller.rb
class Consumers::FermersController < ApplicationController
	layout 'consumer'
  before_action :authenticate_consumer!
  def index
  	@fermers = Fermer.all
    @consumer = current_consumer
    # @bookmarks = Bookmark.where(consumer_id: @consumer.id).all
  end
  def show
  	@fermer = Fermer.find(params[:id])
    @book_mark = BookMark.new
    @review = FermerReview.new
    @reviews = @fermer.fermer_reviews
  end
  private
  def fermer_params
  	params.require(:fermer).permit(:last_name, :first_name, :kana_last_name, :kana_first_name, :postcode,:prefecture_code, :address_city, :address_street, :address_building, :phone,:garden,:home_page,:profile_image)
  end
end

app/controllers/fermers/base.rb
class Fermers::BaseController < ApplicationController
     layout 'fermer'
end

app/controllers/fermers/brands_controller.rb
class Fermers::BrandsController < ApplicationController
	layout 'fermer'
  def index
  end
end

app/controllers/fermers/categories_controller.rb
class Fermers::CategoriesController < ApplicationController
	layout 'fermer'
  def index
  end
end

app/controllers/fermers/columns_controller.rb
class Fermers::ColumnsController < ApplicationController
 layout 'fermer'
 before_action :authenticate_fermer!
 def index
  if params[:fermer_id]
    @columns = Column.where(fermer_id: params[:fermer_id])
  else
    @columns = Column.all
  end
end
def new
  @column = Column.new
  @column.column_images.build
end
def create
  @column = Column.new(column_params)
  @column.fermer_id = current_fermer.id
  if @column.save!
    redirect_to fermers_column_path(@column)
  else
    render "new"
  end
end
def show
   @column = Column.find(params[:id])
   @fermer = current_fermer
   @comments = @column.column_comments
end
def edit
   @column = Column.find(params[:id])
end
def update
  @column = Column.find(params[:id])
  if @column.update(column_params)
    redirect_to fermers_column_path(@column)
  else
    render 'edit'
  end
end
def destroy
  @column = Column.find(params[:id])
  @column.destroy
  redirect_to admins_columns_path
end

private
def column_params
  params.require(:column).permit(:title,:body,:fermer_id,column_images_images:[])
end


end

app/controllers/fermers/confirmations_controller.rb
# frozen_string_literal: true

class Fermers::ConfirmationsController < Devise::ConfirmationsController
  layout 'fermer'
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/fermers/consumers_controller.rb
class Fermers::ConsumersController < ApplicationController
	layout 'fermer'
  before_action :authenticate_fermer!
  def index
  end
  def show
  	@consumer = Consumer.find(params[:id])
  end
  private
  def consumer_params
       params.require(:consumer).permit(:last_name, :first_name, :kana_last_name, :kana_first_name,:gender,:age,:prefecture_code, :address_city,:address_street,:address_building, :postcode, :phone, :email,:withdraw)
  end
end

app/controllers/fermers/fermers_controller.rb
class Fermers::FermersController < ApplicationController
  layout 'fermer'
  before_action :authenticate_fermer!
  def show
  	@fermer = Fermer.find(params[:id])
    @reviews = @fermer.fermer_reviews
  end
  def edit
    @fermer = Fermer.find(params[:id])
    unless current_fermer.nil? || current_fermer.id == current_fermer.id
      flash[:warning] = "アクセス権がありません"
      redirect_to fermers_fermer_path(current_fermer)
    end
  end
  def update
    if current_fermer.update(fermer_params)
      flash[:success] =  "更新に成功しました"
      redirect_to fermers_fermer_path(current_fermer)
    else
      flash[:warning] = "入力内容を確認してください"
      render :edit
    end
  end
  def change
    current_fermer.update(withdraw: true)
    reset_session
    redirect_to root_path
  end
  def withdraw
  end

  private
  def fermer_params
       params.require(:fermer).permit(:last_name, :first_name, :kana_last_name, :kana_first_name,:garden,:home_page,:prefecture_name, :address_city,:address_street,:address_building, :postcode, :phone, :email,:withdraw,:profile_image)
    end
end

app/controllers/fermers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Fermers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  layout 'fermer'
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/fermers/order_products_controller.rb
class Fermers::OrderProductsController < ApplicationController
	layout 'fermer'
	before_action :authenticate_fermer!
	def update
		@order_product = OrderProduct.find(params[:id])
		if @order_product.product_status == "wait_create" && order_product_params[:product_status] == "create"
			@order_product.order.update(order_status: 2)

			@order_product.update!(order_product_params)
			redirect_back(fallback_location: fermers_order_path)
		elsif @order_product.product_status == "create" && order_product_params[:product_status] == "finish"
			@order_product.order.update(order_status: 3)
			@order_product.update!(order_product_params)
			redirect_back(fallback_location: fermers_order_path)
		else
			redirect_back(fallback_location: fermers_order_path)
		end
	end

	private
	def order_product_params
		params.require(:order_product).permit(:product_id,:quantity,:product_status,:price)
	end
end

app/controllers/fermers/orders_controller.rb
class Fermers::OrdersController < ApplicationController
	layout 'fermer'
	before_action :authenticate_fermer!

	def index
		@products = current_fermer.products
	end
	def show
		@order = Order.find(params[:id])
		@total_price = 0
        @order.order_products.each do |order_product|
          @total_price += (order_product.product.unit_price * order_product.quantity)
        end

	end
	def update
		@order = Order.find(params[:id])
		if @order.order_status == "wait" && order_params[:order_status] == "confirm"
				@order.order_products.each do |order_product|
			         order_product.product_status = 1
			    end
			@order.update!(order_params)
			redirect_back(fallback_location: fermers_order_path)
		elsif @order.order_status == "preparation" && order_params[:order_status] == "finish"
			@order.update!(order_params)
			redirect_back(fallback_location: fermers_order_path)
  	    else
  	    	redirect_back(fallback_location: fermers_order_path)
  	    end
  end
	private
	def order_params
		params.require(:order).permit(:member_id,:order_status,:payment_method,:address,:postcode,:name,:postage,:billing_amount,order_products_attributes: [:product_id, :quantity, :product_status, :price])
	end

end

app/controllers/fermers/passwords_controller.rb
# frozen_string_literal: true

class Fermers::PasswordsController < Devise::PasswordsController
  layout 'fermer'
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/fermers/products_controller.rb
class Fermers::ProductsController < ApplicationController
	layout 'fermer'
  def index
    if params[:fermer_id]
      @products = Product.includes(brand: :category).where(categories: {category_status: false},fermer_id: current_fermer.id).page(params[:page]).reverse_order
    else
      @products =Product.all.page(params[:page]).reverse_order
    end
    respond_to do |format|
      format.html do
      end
      format.csv do
          send_data render_to_string, filename: "(ファイル名).csv", type: :csv
      end
    end
  end
  def new
  	@product = Product.new
    @product.product_images.build
    @categories = Category.where(category_status: 'draft').order("name")
    @brands = Brand.where(brand_status: 'draft').order("name")
    @category = Category.new
    @product.build_stock

  end
  def filter_brand
    @product = Product.new
    @product.build_stock
    # @stock = Stock.new
    @product.product_images.build
    @product.category_id = params["category"]["id"]
    @categories = Category.where(category_status: 'draft').order("name")
    @brands = Brand.where(brand_status: 'draft')
    .where(category_id: params["category"]["id"])
    .order("name")
    @category = Category.new
    @category.id = params["category"]["id"]
    render "new"
  end
  def create
  	@product = Product.new(product_params)
    # @product.stock.build(stock_params)
    @product.fermer_id = current_fermer.id
    @product.save
    redirect_to fermers_product_path(@product)
  end
  def show
  	@product = Product.find(params[:id])
    @comments = @product.product_comments
  end
  def edit
  	@product = Product.find(params[:id])
    @product.product_images.build
    @categories = Category.where(category_status: 'draft').order("name")
    @brands = Brand.where(brand_status: 'draft').order("name")
    @category = Category.new
    @product.stocks.build
  end
  def update
  	@product = Product.find(params[:id])
    if @product.update(product_params)
     redirect_to fermers_product_path(@product)
   else
     render 'edit'
   end
 end
 def sale_status
   
 end
 def destroy
   @product = Product.find(params[:id])
   @product.destroy
   redirect_to fermers_products_path
 end
 private
 def product_params
   params.require(:product).permit(:name,:sale_status,:introduction,:category_id,:brand_id,:quantity,:stock_id,:fermer_id,:unit_price, product_images_images: [],stock_attributes: [:product_id, :quantity])
 end
end

app/controllers/fermers/registrations_controller.rb
# frozen_string_literal: true

class Fermers::RegistrationsController < Devise::RegistrationsController
  protect_from_forgery
  layout 'fermer'
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
   def create
    build_resource(sign_up_params)
    resource.save
     yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
        SignUpMailer.send_mail_fermer(current_fermer).deliver_now
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
     @fermer = current_fermer
     @fermer.update(name: @fermer.last_name + @fermer.first_name)
     @fermer.update(address: @fermer.prefecture_name +  @fermer.address_city + @fermer.address_street + @fermer.address_building)
   end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/fermers/searches_controller.rb
class Fermers::SearchesController < ApplicationController
end

app/controllers/fermers/stocks_controller.rb
class Fermers::StocksController < ApplicationController
end

app/views/fermers/fermers/edit.html.erb
<div class="row" style= "width: 80%; margin: 20px auto;">
  <div class="form-horizontal">
    <h4 style="margin-bottom: 20px; border-left: 2px solid #2D6F4C; padding: 10px;">プロフィール編集画面</h4>
  </div>
</div>
<div class="row my-3">
  <div class="offset-3 col-6">

    <%= form_for(@fermer, url:fermers_fermer_path,  local: true) do |f| %>
    <div class="form-group">
      <%= f.label :プロフィール画像, class: "brown-border px-3" %>
      <%= f.attachment_field :profile_image %>
    </div>
    <div class="form-group">
      <%= f.label :氏名, class: "brown-border px-3" %>
      <div class="row">
        <%= f.text_field :last_name, class: "form-control col-4"%>
        <%= f.text_field :first_name, class: "brown-border px-3" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :フリガナ, class: "brown-border px-3" %>
      <div class="row">
        <%= f.text_field :kana_last_name, class: "form-control offset-1 col-4"%>
          <%= f.text_field :kana_first_name, class: "form-control col-4"%>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :農園名, class: "brown-border px-3" %>
      <%= f.text_field :garden, class: "form-control offset-1 col-8"%>
    </div>
  <div class="form-group">
    <%= f.label :ホームページ, class: "brown-border px-3" %>
    <%= f.text_field :home_page, class: "form-control offset-1 col-8"%>
  </div>
  <div class="form-group">
    <%= f.label :電話番号, class: "brown-border px-3" %>
    <%= f.text_field :phone, class: "form-control offset-1 col-8"%>
  </div>
  <div class="form-group">
    <%= f.label :メールアドレス, class: "brown-border px-3" %>
    <%= f.email_field :email, class: "form-control offset-1 col-8"%>
  </div>
  <div class="field">
   <%= f.label :郵便番号, class: "brown-border px-3" %>
   <%= f.text_field :postcode, class: "form-control offset-1 col-8"%>
 </div>
 <div class="field">
   <%= f.label :都道府県, class: "brown-border px-3" %>
   <%= f.collection_select :prefecture_code, JpPrefecture::Prefecture.all, :code, :name %>
 </div>
 <div class="field">
   <%= f.label :市町村, class: "brown-border px-3" %>
   <%= f.text_field :address_city, class: "form-control offset-1 col-8" %>
 </div>
 <div class="field">
  <%= f.label :番地, class: "brown-border px-3" %>
  <%= f.text_field :address_street, class: "form-control offset-1 col-8" %>
</div>
<div class="field">
 <%= f.label :建物, class: "brown-border px-3" %>
 <%= f.text_field :address_building, class: "form-control offset-1 col-8" %>
</div>


<div class="row">
  <%= f.submit "編集内容を保存する", class: "btn btn-outline-success offset-3 mt-3" %>
</div>
<% end %>

</div>

<div class="col-2 d-flex flex-column align-items-end">
  <%= link_to "退会する" ,fermers_fermers_withdraw_path,method: :get, class: "btn btn-danger mt-auto" %>
</div>
</div>

app/views/fermers/fermers/show.html.erb
<h1>マイページ</h1>
<div class="row" style= "width: 80%; margin: 20px auto;">
	<div class="form-horizontal">
		<h4 style="margin-bottom: 20px; border-left: 2px solid #2D6F4C; padding: 10px;">マイページ</h4>
	</div>
</div>

<div class="show-container" style="width:50%; margin: 20px auto;">
	<table class="table table-bordered">
		<tr>
			<th style=“background-color: #DAD7D7; border-bottom: 1px solid #fff;“>氏名</th>
			<td><%= @fermer.name %></td>
		</tr>
		<tr>
			<th style=“background-color: #DAD7D7; border-bottom: 1px solid #fff;“>プロフィール画像</th>
			<td>
				<% if @fermer.profile_image.present? %>
	     			<%= attachment_image_tag @fermer,:profile_image, :fill, 200, 200 %>
				<% else %>
					<%= image_tag 'no_image.jpg',size: '200*200'%>
				<% end %>
			</td>
		</tr>
		<tr>
			<th style=“background-color: #DAD7D7; border-bottom: 1px solid #fff;“>電話番号</th>
			<td><%= @fermer.phone %></td>
		</tr>
		<tr>
			<th style=“background-color: #DAD7D7; border-bottom: 1px solid #fff;“>メールアドレス</th>
			<td style=“border-bottom: 1px solid #DAD7D7;“><%= @fermer.email %></td>
		</tr>
	</table>

	<table>
		<td><h5>登録情報</h5>
			<%= link_to '編集する', edit_fermers_fermer_path, class: "btn btn-outline-primary" %>
		</td>
	</table>
</div>
	<div class="container">
		<div class="row">
			<div class="col-md-10">
				<div class="outer">
					<table class="table table-striped">
						<thead class="thead-dark">
							<tr>
								<th>投稿者</th>
								<th>性別•年齢</th>
								<th>コメント日時</th>
								<th>評価</th>
								<th>星</th>
								<th>コメント</th>
								<th colspan="3"></th>
							</tr>
						</thead>
						<tbody>
							<% if @reviews.present? %>
								<% @reviews.each do |review| %>
								    <div class="row comments">
								      	<div class="col-md-2 comments-consumer">
									        <td class="posts-title"><%= link_to "#{review.consumer.name}さん", consumers_consumer_path(review.consumer.id) %></td>
									        <td class="posts-prof"><%= review.consumer.gender_i18n %> <%= review.consumer.age_i18n %></td>
								    	</div>
									    <div class="col-md-6 mb-3">
								        	<div class=" comments-consumer">
								          		<td><%= l review.created_at, format: :short %></td>
								          		<td class="mb-3">評価：<%= review.rate %>点 | <%= review.title %></td>
								         		<td id="star-rate-<%= review.id %>"></td>
									          <script>
									          $('#star-rate-<%= review.id %>').raty({
									            size: 36,
									            starOff:  '<%= asset_path('star-off.png') %>',
									            starOn : '<%= asset_path('star-on.png') %>',
									            starHalf: '<%= asset_path('star-half.png') %>',
									            half: true,
									            readOnly: true,
									            score: <%= review.rate %>,
									          });
									          </script>
								        		<td><%= review.comment %></td>
								        	</div>
								        </div>
								    </div>
							    <% end %>
						    <% end %>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/fermers/fermers/withdraw.html.erb
<div class="container my-5">
  <div class="row">
    <div class="offset-1">
      <h1 class="red-border px-3">本当に退会しますか？</h1>
    </div>
  </div>
  <div class="row my-5">
    <div class="offset-2">
      <p>退会すると、会員登録情報やこれまでの購入履歴が閲覧できなくなります。</p>
      <p>退会する場合は、「退会する」をクリックしてください。</p>
    </div>
  </div>
  <div >
    <div class="offset-3 col-2">
   <%= link_to "退会しない" ,root_path(@fermer) %>
    </div>
    <div class="offset-2 col-2">
    <%= link_to "退会する" , fermers_fermers_change_path,method: :patch %>
    </div>
  </div>
</div>