config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  get '/search' => 'homes#search'
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :consumers, controllers: {
    sessions:      'consumers/sessions',
    passwords:     'consumers/passwords',
    registrations: 'consumers/registrations'
  }

  devise_for :fermers, controllers: {
    sessions:      'fermers/sessions',
    passwords:     'fermers/passwords',
    registrations: 'fermers/registrations'
  }

    namespace :consumers do
      get 'consumers/withdraw'=> 'consumers#withdraw'
      patch 'consumers/change' => 'consumers#change'
      put 'consumers/change' => 'consumers#change'
      get '/search' => 'searches#search'
      resources :searches,only: [:index]
      resources :consumers,only: [:edit,:update,:show]
      resources :cards,only: [:create,:destroy]
      resources :fermers do
        resources :fermer_reviews,only: [:index,:show,:create,:destroy]
        resource :book_marks,only: [:create,:destroy]
      end
      resources :columns do
        resource :column_comments,only: [:index,:show,:create,:destroy], shallow: true
        resource :column_favorites,only: [:create,:destroy], shallow: true
      end
      resources :cart_products,only: [:index,:create,:update,:destroy]
      resources :destinations ,only: [:show,:index,:edit,:update,:create,:destroy]
      resources :products ,only: [:show,:index] do
        resource :product_comment,only: [:show,:create,:destroy], shallow: true
        resource :product_favorite,only: [:create,:destroy], shallow: true
      end
      get 'orders/confirm' => 'orders#confirm'
      post 'orders/pay' => 'orders#pay'
      get 'orders/finish' => 'orders#finish'
      resources :orders ,only: [:new,:create,:index,:show]
      delete 'consumers/cart_products/destroy_all'  => 'cart_products#destroy_all'
    end


    namespace :fermers do
      resources :fermers,only:[:show,:edit,:update]
      get '/search' => 'searches#search'
      get 'fermers/withdraw'=> 'fermers#withdraw'
      patch 'fermers/change' => 'fermers#change'
      put 'fermers/change' => 'fermers#change'
      resources :searches,only: [:index]
      post 'products/filter_brand' => 'products#filter_brand'
      resources :columns
      resources :columns_comments,only: [:index,:show], shallow: true
      resources :columns_favorites,only: [:index], shallow: true
      resources :products
      resources :products_comments,only: [:index,:show], shallow: true
      resources :products_favorites,only: [:index], shallow: true
      resources :order_products,only: [:update]
      resources :orders,only: [:show,:index,:update]
      resources :consumers,only: [:show,:index]
      resources :addresses ,only: [:show,:index,:edit,:update,:create,:destroy]
    end


    namespace :admins do
      get 'homes/top'
      get '/search' => 'searches#search'
      resources :searches,only: [:index]
      resources :consumers,only: [:show,:index,:destroy]
      resources :fermers,only: [:index,:show,:destroy]
      resources :categories,only: [:index,:create,:edit,:update,:destroy]
      resources :brands,only: [:index,:create,:edit,:update,:destroy]
      resources :products,only: [:index,:show,:destroy]
      resources :orders,only: [:show,:index,:destroy]
      resources :columns,only: [:index,:show,:destroy]
      resources :column_comments,only: [:index,:show]
      resources :products_comments,only: [:index,:show]
    end
end

app/models/fermer.rb
class Fermer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
        has_many :book_marks, dependent: :destroy
        has_many :consumers, through: :book_marks
        attachment :profile_image

        has_many :columns, dependent: :destroy
        has_many :products, dependent: :destroy
        has_many :fermer_reviews, dependent: :destroy

         enum withdraw: { draft: false, published: true }

        def book_marked_by?(consumer)
          book_marks.where(consumer_id: consumer.id).exists?
        end


include JpPrefecture
  jp_prefecture :prefecture_code

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end
end

app/controllers/admins/fermers_controller.rb
class Admins::FermersController < ApplicationController
	layout 'admin'
  before_action :authenticate_admin!
  def index
  	@fermers = Fermer.all
  end
  def show
  	@fermer = Fermer.find(params[:id])
    @reviews = @fermer.fermer_reviews
  end
  private
  def fermer_params
  	params.require(:fermer).permit(:last_name, :first_name, :kana_last_name, :kana_first_name, :postcode,:prefecture_code, :address_city, :address_street, :address_building, :phone,:garden,:home_page,:profile_image)
  end
end

app/controllers/admins/products_controller.rb
class Admins::ProductsController < ApplicationController
	layout 'admin'
  before_action :authenticate_admin!
  def index
  	@products = Product.all
  end
  def show
  	@product = Product.find(params[:id])
    @comments = @product.product_comments
  end
  private
  def product_params
    params.require(:product).permit(:name,:sale_status,:introduction,:category_id,:brand_id,:quantity,:stock_id,:fermer_id,:unit_price,product_images_images: [])
  end
end

app/controllers/consumers/fermers_controller.rb
class Consumers::FermersController < ApplicationController
	layout 'consumer'
  before_action :authenticate_consumer!
  def index
  	@fermers = Fermer.all
    @consumer = current_consumer
    # @bookmarks = Bookmark.where(consumer_id: @consumer.id).all
  end
  def show
  	@fermer = Fermer.find(params[:id])
    @book_mark = BookMark.new
    @review = FermerReview.new
    @reviews = @fermer.fermer_reviews
  end
  private
  def fermer_params
  	params.require(:fermer).permit(:last_name, :first_name, :kana_last_name, :kana_first_name, :postcode,:prefecture_code, :address_city, :address_street, :address_building, :phone,:garden,:home_page,:profile_image)
  end
end

app/controllers/consumers/products_controller.rb
class Consumers::ProductsController < ApplicationController
	layout 'consumer'
  def index
  	@categories = Product.includes(brand: :category).where(categories: {category_status: false})
  	@blands = Product.joins(:brand).where(brands:  {brand_status: false})
  	if params[:fermer_id]
  		@products = Product.joins({:brand => :category}).where(fermer_id: params[:fermer_id]).where("(category_status = ?) AND (brand_status = ?) AND (sale_status = ?)",false,false,0).page(params[:page]).reverse_order
  	elsif params[:brand_id]
  	    @products = Product.where(sale_status: 0).where(brand_id: params[:brand_id]).page(params[:page]).reverse_order
  	else
  		@products = Product.joins({:brand => :category}).where("(category_status = ?) AND (brand_status = ?) AND (sale_status = ?)",false,false,0).page(params[:page]).reverse_order
  	end
  end

  def show
  	@product = Product.find(params[:id])
    @cart = CartProduct.new
    @comment = ProductComment.new
    @comments = @product.product_comments
    @products = Product.all
  end
  private
  def product_params
  	params.require(:product).permit(:name,:sale_status,:introduction,:category_id,:brand_id,:quantity,:stock_id,:fermer_id,:unit_price,product_images_images: [])
  end
end

app/controllers/fermers/base.rb
class Fermers::BaseController < ApplicationController
     layout 'fermer'
end

app/controllers/fermers/brands_controller.rb
class Fermers::BrandsController < ApplicationController
	layout 'fermer'
  def index
  end
end

app/controllers/fermers/categories_controller.rb
class Fermers::CategoriesController < ApplicationController
	layout 'fermer'
  def index
  end
end

app/controllers/fermers/columns_controller.rb
class Fermers::ColumnsController < ApplicationController
 layout 'fermer'
 before_action :authenticate_fermer!
 def index
  if params[:fermer_id]
    @columns = Column.where(fermer_id: params[:fermer_id])
  else
    @columns = Column.all
  end
end
def new
  @column = Column.new
  @column.column_images.build
end
def create
  @column = Column.new(column_params)
  @column.fermer_id = current_fermer.id
  if @column.save!
    redirect_to fermers_column_path(@column)
  else
    render "new"
  end
end
def show
   @column = Column.find(params[:id])
   @fermer = current_fermer
   @comments = @column.column_comments
end
def edit
   @column = Column.find(params[:id])
end
def update
  @column = Column.find(params[:id])
  if @column.update(column_params)
    redirect_to fermers_column_path(@column)
  else
    render 'edit'
  end
end
def destroy
  @column = Column.find(params[:id])
  @column.destroy
  redirect_to admins_columns_path
end

private
def column_params
  params.require(:column).permit(:title,:body,:fermer_id,column_images_images:[])
end


end

app/controllers/fermers/confirmations_controller.rb
# frozen_string_literal: true

class Fermers::ConfirmationsController < Devise::ConfirmationsController
  layout 'fermer'
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/fermers/consumers_controller.rb
class Fermers::ConsumersController < ApplicationController
	layout 'fermer'
  before_action :authenticate_fermer!
  def index
  end
  def show
  	@consumer = Consumer.find(params[:id])
  end
  private
  def consumer_params
       params.require(:consumer).permit(:last_name, :first_name, :kana_last_name, :kana_first_name,:gender,:age,:prefecture_code, :address_city,:address_street,:address_building, :postcode, :phone, :email,:withdraw)
  end
end

app/controllers/fermers/fermers_controller.rb
class Fermers::FermersController < ApplicationController
  layout 'fermer'
  before_action :authenticate_fermer!
  def show
  	@fermer = Fermer.find(params[:id])
    @reviews = @fermer.fermer_reviews
  end
  def edit
    @fermer = Fermer.find(params[:id])
    unless current_fermer.nil? || current_fermer.id == current_fermer.id
      flash[:warning] = "アクセス権がありません"
      redirect_to fermers_fermer_path(current_fermer)
    end
  end
  def update
    if current_fermer.update(fermer_params)
      flash[:success] =  "更新に成功しました"
      redirect_to fermers_fermer_path(current_fermer)
    else
      flash[:warning] = "入力内容を確認してください"
      render :edit
    end
  end
  def change
    current_fermer.update(withdraw: true)
    reset_session
    redirect_to root_path
  end
  def withdraw
  end

  private
  def fermer_params
       params.require(:fermer).permit(:last_name, :first_name, :kana_last_name, :kana_first_name,:garden,:home_page,:prefecture_name, :address_city,:address_street,:address_building, :postcode, :phone, :email,:withdraw,:profile_image)
    end
end

app/controllers/fermers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Fermers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  layout 'fermer'
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/fermers/order_products_controller.rb
class Fermers::OrderProductsController < ApplicationController
	layout 'fermer'
	before_action :authenticate_fermer!
	def update
		@order_product = OrderProduct.find(params[:id])
		if @order_product.product_status == "wait_create" && order_product_params[:product_status] == "create"
			@order_product.order.update(order_status: 2)

			@order_product.update!(order_product_params)
			redirect_back(fallback_location: fermers_order_path)
		elsif @order_product.product_status == "create" && order_product_params[:product_status] == "finish"
			@order_product.order.update(order_status: 3)
			@order_product.update!(order_product_params)
			redirect_back(fallback_location: fermers_order_path)
		else
			redirect_back(fallback_location: fermers_order_path)
		end
	end

	private
	def order_product_params
		params.require(:order_product).permit(:product_id,:quantity,:product_status,:price)
	end
end

app/controllers/fermers/orders_controller.rb
class Fermers::OrdersController < ApplicationController
	layout 'fermer'
	before_action :authenticate_fermer!

	def index
		@products = current_fermer.products
	end
	def show
		@order = Order.find(params[:id])
		@total_price = 0
        @order.order_products.each do |order_product|
          @total_price += (order_product.product.unit_price * order_product.quantity)
        end

	end
	def update
		@order = Order.find(params[:id])
		if @order.order_status == "wait" && order_params[:order_status] == "confirm"
				@order.order_products.each do |order_product|
			         order_product.product_status = 1
			    end
			@order.update!(order_params)
			redirect_back(fallback_location: fermers_order_path)
		elsif @order.order_status == "preparation" && order_params[:order_status] == "finish"
			@order.update!(order_params)
			redirect_back(fallback_location: fermers_order_path)
  	    else
  	    	redirect_back(fallback_location: fermers_order_path)
  	    end
  end
	private
	def order_params
		params.require(:order).permit(:member_id,:order_status,:payment_method,:address,:postcode,:name,:postage,:billing_amount,order_products_attributes: [:product_id, :quantity, :product_status, :price])
	end

end

app/controllers/fermers/passwords_controller.rb
# frozen_string_literal: true

class Fermers::PasswordsController < Devise::PasswordsController
  layout 'fermer'
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/fermers/products_controller.rb
class Fermers::ProductsController < ApplicationController
	layout 'fermer'
  def index
    if params[:fermer_id]
      @products = Product.includes(brand: :category).where(categories: {category_status: false},fermer_id: current_fermer.id).page(params[:page]).reverse_order
    else
      @products =Product.all.page(params[:page]).reverse_order
    end
    respond_to do |format|
      format.html do
      end
      format.csv do
          send_data render_to_string, filename: "(ファイル名).csv", type: :csv
      end
    end
  end
  def new
  	@product = Product.new
    @product.product_images.build
    @categories = Category.where(category_status: 'draft').order("name")
    @brands = Brand.where(brand_status: 'draft').order("name")
    @category = Category.new
    @product.build_stock

  end
  def filter_brand
    @product = Product.new
    @product.build_stock
    # @stock = Stock.new
    @product.product_images.build
    @product.category_id = params["category"]["id"]
    @categories = Category.where(category_status: 'draft').order("name")
    @brands = Brand.where(brand_status: 'draft')
    .where(category_id: params["category"]["id"])
    .order("name")
    @category = Category.new
    @category.id = params["category"]["id"]
    render "new"
  end
  def create
  	@product = Product.new(product_params)
    # @product.stock.build(stock_params)
    @product.fermer_id = current_fermer.id
    @product.save
    redirect_to fermers_product_path(@product)
  end
  def show
  	@product = Product.find(params[:id])
    @comments = @product.product_comments
  end
  def edit
  	@product = Product.find(params[:id])
    @product.product_images.build
    @categories = Category.where(category_status: 'draft').order("name")
    @brands = Brand.where(brand_status: 'draft').order("name")
    @category = Category.new
    @product.stocks.build
  end
  def update
  	@product = Product.find(params[:id])
    if @product.update(product_params)
     redirect_to fermers_product_path(@product)
   else
     render 'edit'
   end
 end
 def sale_status
   
 end
 def destroy
   @product = Product.find(params[:id])
   @product.destroy
   redirect_to fermers_products_path
 end
 private
 def product_params
   params.require(:product).permit(:name,:sale_status,:introduction,:category_id,:brand_id,:quantity,:stock_id,:fermer_id,:unit_price, product_images_images: [],stock_attributes: [:product_id, :quantity])
 end
end

app/controllers/fermers/searches_controller.rb
class Fermers::SearchesController < ApplicationController
end

app/views/fermers/products/edit.html.erb
<label>
	<div class="row" style= "width: 80%; margin: 20px auto;">
		<div class="form-horizontal">
			<h4 style="margin-bottom: 20px; border-left: 2px solid #2D6F4C; padding: 10px;">商品新規登録画面</h4>
		</div>
	</div>
</label>


<%= form_for(@product,url:fermers_products_path) do |f| %>
<% if @product.errors.any? %>

<h3><%= @product.errors.count %>error occurrence</h3>
<ul>
	<% @product.errors.full_messages.each do |message| %>
	<li><%= message %></li>
	<% end %>
</ul>
<% end %>

<div class="container">
	<div class="row">
		<div class="col-md-6">
			<div class="form-group">
				<label>
					<%= f.label :カテゴリー %>
					<%= f.collection_select :category_id, @categories, :id, :name,include_blank: true %>
				</label>
			</div>
			<div class="form-group">
				<label>
					<%= f.label :ブランド %>
					<%= f.collection_select :brand_id, @brands, :id, :name,include_blank: true %>
				</label>
			</div>
			<div class="form-group">
				<label>
					<%= f.label :画像選択 %>
					<%= f.attachment_field :product_images_images, multiple: true %>
				</label>
			</div>

			<div class="form-group">
				<label>
					<%= f.label :商品名 %>
					<%= f.text_field :name, class:"form-control", id:"InputName", autocomplete: "name" %>
				</label>
			</div>

			<div class="form-group">
				<label>
					<%= f.label :商品説明 %>
					<%= f.text_area :introduction, class:"form-control", id:"InputIntroduction", autocomplete: "introduction", rows: 6 %>
				</label>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-6">
			<div class="form-group">
				<label>
					<%= f.label :税抜価格 %><br>
					<%= f.text_field :unit_price, class:"form-control"%>
				</label>
			</div>

			<div class="form-group">
				<label>
					<%= f.label :販売ステータス %>
					<%= f.select :sale_status, Product.sale_statuses_i18n.keys.map { |k| [Product.sale_statuses_i18n[k], k]} %>
				</label>
			</div>
			<div class="form-group">
				<label>
					<%= f.label :在庫数 %>
					<%= f.fields_for :stocks do |o| %>
						<%= o.number_field :quantity, class:"form-control"%>
					<% end %>
				</label>
			</div>
		</div>
	</div>

	<div class="form-group">
		<label>
			<%= f.submit class: "btn btn-primary col-xs-12" %>
		</div>
	</label>
	<div>
		<%= link_to "戻る",admins_products_path,class: "btn btn-success col-xs-12"%>
	</div>
</div>
<% end %>
<%= form_for(@category, url: fermers_products_filter_brand_path) do |f| %>
<%= f.hidden_field :id %>
<% end %>
<script type="text/javascript">
	$(function(){
		$(document).on("change", "#product_category_id", function() {
			console.log("test")
			$("#category_id").val($(this).val());
			$(".new_category").submit();
		});
	});
</script>

app/views/fermers/products/index.html.erb
<div class="row" style= "width: 80%; margin: 20px auto;">
	<div class="form-horizontal">
		<h4 style="margin-bottom: 20px; border-left: 2px solid #2D6F4C; padding: 10px;">商品一覧画面</h4>
	</div>
</div>
<div class="container" style="position:relative;">
	<div class="outer">
		<table class="table table-striped">
			<%= link_to "CSV出力", fermers_products_path(format: :csv), class: "btn btn-primary" %>
			<thead class="thead-dark">
				<tr>
					<th class="col-xs-3">イメージ</th>
					<th class="col-xs-2">商品名</th>
					<th class="col-xs-1">税抜き価格</th>
					<th class="col-xs-2">カテゴリー</th>
					<th class="col-xs-2">ブランド</th>
					<th class="col-xs-2">農園名</th>
				</tr>
			</thead>
			<tbody>
				<%if @products.present? %>
					<% @products.each do |product| %>
						<tr>
							<td>
								<%= link_to(fermers_product_path(product)) do %>
								  <% if product.product_images.present? %>
								      <%= attachment_image_tag product.product_images.first, :image, :fill, 200, 200 %>
								  <% else %>
								    <%= image_tag 'no_image.jpg',size: '200*200'%>
								  <% end %>
								<% end %>
							</td>
							<td><%= link_to(fermers_product_path(product)) do %>
								<%= product.name %>
								<% end %>
							</td>
							<td><%= product.unit_price %></td>
							<td><%= product.brand.category.name %></td>
							<td><%= product.brand.name %></td>
							<td><%= product.fermer.garden %></td>
						</tr>
					<% end %>
				<% end %>
			</tbody>
		</table>
	</div>
	<%= paginate @products, class: "paginate" %>
	<div class="text-right">
		<%= link_to "新規作成",new_fermers_product_path,class: "btn btn-success col-xs-12"%>
	</div>
</div>

app/views/fermers/products/new.html.erb
<label>
	<div class="row" style= "width: 80%; margin: 20px auto;">
		<div class="form-horizontal">
			<h4 style="margin-bottom: 20px; border-left: 2px solid #2D6F4C; padding: 10px;">商品新規登録画面</h4>
		</div>
	</div>
</label>


<%= form_for(@product,url:fermers_products_path) do |f| %>
	<% if @product.errors.any? %>
		<h3><%= @product.errors.count %>error occurrence</h3>
		<ul>
			<% @product.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	<% end %>
	<div class="container">
		<div class="row">
			<div class="col-md-6">
				<div class="form-group">
					<label>
						<%= f.label :カテゴリー %>
						<%= f.collection_select :category_id, @categories, :id, :name,include_blank: true %>
					</label>
				</div>
				<div class="form-group">
					<label>
						<%= f.label :ブランド %>
						<%= f.collection_select :brand_id, @brands, :id, :name,include_blank: true %>
					</label>
				</div>
				<div class="form-group">
					<label>
						<%= f.label :画像選択 %>
						<%= f.attachment_field :product_images_images, multiple: true %>
					</label>
				</div>

				<div class="form-group">
					<label>
						<%= f.label :商品名 %>
						<%= f.text_field :name, class:"form-control", id:"InputName", autocomplete: "name" %>
					</label>
				</div>

				<div class="form-group">
					<label>
						<%= f.label :商品説明 %>
						<%= f.text_area :introduction, class:"form-control", id:"InputIntroduction", autocomplete: "introduction", rows: 6 %>
					</label>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-6">
				<div class="form-group">
					<label>
						<%= f.label :税抜価格 %><br>
						<%= f.text_field :unit_price, class:"form-control"%>
					</label>
				</div>

				<div class="form-group">
					<label>
						<%= f.label :販売ステータス %>
						<%= f.select :sale_status, Product.sale_statuses_i18n.keys.map { |k| [Product.sale_statuses_i18n[k], k]} %>
					</label>
				</div>
				<div class="form-group">
					<label>
						<%= f.label :在庫数 %>
						<%= f.fields_for :stock do |o| %>
							<%= o.number_field :quantity, class:"form-control"%>
						<% end %>
					</label>
				</div>
			</div>
		</div>
		<div class="form-group">
			<label>
				<%= f.submit class: "btn btn-primary col-xs-12" %>
			</label>
		</div>
		<div>
			<%= link_to "戻る",admins_products_path,class: "btn btn-success col-xs-12"%>
		</div>
	</div>
<% end %>
<%= form_for(@category, url: fermers_products_filter_brand_path) do |f| %>
	<%= f.hidden_field :id %>
<% end %>
<script type="text/javascript">
	$(function(){
		$(document).on("change", "#product_category_id", function() {
			console.log("test")
			$("#category_id").val($(this).val());
			$(".new_category").submit();
		});
	});
</script>

app/views/fermers/products/show.html.erb
<div class="container">
	<div class="row" style= "width: 80%; margin: 20px auto;">
		<div class="form-horizontal">
			<h4 style="margin-bottom: 20px; border-left: 2px solid #2D6F4C; padding: 10px;">商品詳細画面</h4>
		</div>
    </div>
	<div class="row" style="width: 80%; margin: 50px auto;">
		<div class= "col-md-6">
			<% if @product.product_images.present? %>
			  <% @product.product_images.each do |image| %>
			    <%= attachment_image_tag image, :image, :fill, 200, 200 %>
			  <% end %>
			<% else %>
			    <%= image_tag 'no_image.jpg',size: '200*200'%>
			<% end %>
		</div>
		<div class= "col-md-6">
			<table class="table table-condensed">
				<tr>
					<th>商品名</th>
					<td><%= @product.name %></td>
				</tr>
				<tr>
					<th>商品説明</th>
					<td><%= @product.introduction %></td>
				</tr>
				<tr>
					<th>カテゴリー</th>
					<td><%= @product.brand.category.name %></td>
				</tr>
				<tr>
					<th>ブランド</th>
					<td><%= @product.brand.name %></td>
				</tr>
				<tr>
					<th>税込価格</th>
					<td><%= @product.unit_price %>円</td>
				</tr>
				<tr>
					<th>在庫個数</th>
					<td><%= @product.stock.quantity %>個</td>
				</tr>
				<tr>
					<th>販売ステータス</th>
					<td><%= @product.sale_status_i18n %></td>
				</tr>
			</table>
		</div>
	</div>
</div>

<div class="container">
	<table>
		<td><%= link_to "⇦戻る",fermers_products_path %></td>
	</table>
	<tabel>
		<div class="text-right">
	<td><%= link_to "編集する" ,edit_fermers_product_path(@product),class: "btn btn-primary col-xs-12" %></td>
	<td><%= link_to "削除する",fermers_product_path(@product.id), method: :delete, data: { confirm:"Are you sure?"} , :class =>"btn btn-danger" %></td>
	</table>
</div>
<div class="container">
	<div class="row">
		<div class= "col-md-12"style=" margin-top: 50px;">
			<div class="outer">
				<table class="table table-striped">
					<thead class="thead-dark">
						<tr>
							<th class="col-xs-1">投稿者</th>
							<th class="col-xs-2">性別•年齢</th>
							<th class="col-xs-1">コメント日時</th>
							<th class="col-xs-2">評価</th>
							<th class="col-xs-2">星</th>
							<th class="col-xs-4">コメント</th>
							<th colspan="3"></th>
						</tr>
					</thead>
					<tbody id="comments_area">
								<%= render partial: 'consumers/product_comments/index', locals: { comments: @comments, product: @product  } %>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>